### PR TITLE
Add support for video source snapshots

### PR DESCRIPTION
**Pull request by DmitrySamoylov**
Story details: https://app.clubhouse.io/lumeo/story/3341

### CODE REVIEW

**Review by jplatte — COMMENTED** [review]
Why enable `uuid`s `v4` feature? I cant see a call to `Uuid::new_v4`.

**Comment by DmitrySamoylov** [comment]
Here it is:
https://github.com/lumeohq/lumeo-types-rs/blob/4a2e65d13334787dd86da677292ff92c3017c0cd/commands/src/api/mod.rs#L66

**Comment by jplatte** [comment]
I was only looking at the changes from this PR. So really the feature should have been enabled before? Okay then.

**Review by jplatte — APPROVED** [review]

**Comment by DmitrySamoylov** [comment]
Just checked and it seems that we don't use `Request::new()` anywhere in lumeod or in api-server. So removing it.

**Pull request merged**
